# Generated by Django 4.2.22 on 2025-06-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmaliyModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmaliyMavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_description', models.TextField(help_text="Bu darsda nima o'rganiladi")),
                ('step_by_step_guide', models.TextField(help_text='Bosqichma-bosqich qanday qilish')),
                ('code_example', models.TextField(blank=True, help_text='Agar VBA kodi kerak bo‘lsa', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Qo‘shimcha tushuntirish yoki eslatma', null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='amaliy_fayllar/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macros.amaliymodul')),
            ],
        ),
    ]
