# Generated by Django 4.2.22 on 2025-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_testmodul_testsavol_testnatija'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testnatija',
            old_name='score',
            new_name='correct_answers',
        ),
        migrations.RenameField(
            model_name='testnatija',
            old_name='date_taken',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='testsavol',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='testsavol',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='testsavol',
            name='order',
        ),
        migrations.AddField(
            model_name='testnatija',
            name='percentage',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
