# Generated by Django 4.2.22 on 2025-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0004_rename_score_testnatija_correct_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnatija',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='testnatija',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='testnatija',
            name='grade',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testnatija',
            name='score_percent',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testnatija',
            name='wrong_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testnatija',
            name='correct_answers',
            field=models.IntegerField(),
        ),
    ]
