# Generated by Django 4.2.22 on 2025-06-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macros', '0005_remove_testnatija_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('example_file', models.FileField(blank=True, null=True, upload_to='topshiriq_examples/')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopshiriqModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YuborilganTopshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='yechimlar/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Yuborilgan'), ('reviewed', 'Tekshirilgan'), ('rejected', 'Qaytarilgan')], default='pending', max_length=20)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macros.topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topshiriq',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macros.topshiriqmodul'),
        ),
    ]
